ControleDeContatos/Controllers/ContatoController.cs
using ControleDeContatos.Models;
using ControleDeContatos.Repositorio;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;

namespace ControleDeContatos.Controllers
{
    public class ContatoController : Controller
    {
        private readonly iContatoRepositorio _contatoRepositorio;
        public ContatoController(iContatoRepositorio contatoRepositorio)
        {
            _contatoRepositorio = contatoRepositorio;
        }

        public IActionResult Index()
        {
            List<ContatoModel> contatos = _contatoRepositorio.BuscarTodos();
            return View(contatos);
        }

        public IActionResult Adicionar()
        {
            return View();
        }

        public IActionResult Editar(int ID)
        {
            ContatoModel contato = _contatoRepositorio.BuscarPorID(ID);
            return View(contato);
        }

        public IActionResult ExcluirConfirmacao(int ID)
        {
            ContatoModel contato = _contatoRepositorio.BuscarPorID(ID);
            return View(contato);
        }

        public IActionResult Excluir(int ID)
        {
            try
            {
                bool excluido = _contatoRepositorio.Excluir(ID);

                if (excluido)
                {
                    TempData["MensagemSucesso"] = "Contato excluido com sucesso!";
                }
                else
                {
                    TempData["MensagemSucesso"] = "Ops!, não foi possível excluir seu contato, tente novamente!";
                }

                return RedirectToAction("Index");
            }
            catch (Exception error)
            {
                TempData["MensagemSucesso"] = "Ops!, não foi possível excluir seu contato, tente novamente!" + " Error: " + error.Message;
                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        public IActionResult Adicionar(ContatoModel contato)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _contatoRepositorio.Adicionar(contato);
                    TempData["MensagemSucesso"] = "Contato cadastrado com sucesso!";
                    return RedirectToAction("Index");
                }

                return View(contato);
            }
            catch (Exception error)
            {
                TempData["MensagemErro"] = "Ops!, não foi possível cadastrar seu contato, tente novamente!" + " Error: " + error.Message;
                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        public IActionResult Alterar(ContatoModel contato)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _contatoRepositorio.AlterarContato(contato);
                    TempData["MensagemSucesso"] = "Contato alterado com sucesso!";
                    return RedirectToAction("Index");
                }

                return View("Editar", contato);
            }
            catch (Exception error)
            {
                TempData["MensagemErro"] = "Ops!, não foi possível alterar seu contato, tente novamente!" + " Error: " + error.Message;
                return RedirectToAction("Index");
            }
        }
    }
}

ControleDeContatos/Controllers/ProdutoController.cs
using ControleDeContatos.Models;
using ControleDeContatos.Repositorio;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ControleDeContatos.Controllers
{
    public class ProdutoController : Controller
    {
        private readonly iProdutoRepositorio _produtoRepositorio;
        public ProdutoController(iProdutoRepositorio produtoRepositorio)
        {
            _produtoRepositorio = produtoRepositorio;
        }

        public IActionResult Index()
        {
            List<ProdutoModel> produtos = _produtoRepositorio.BuscarTodos();
            return View(produtos);
        }

        public IActionResult Adicionar()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Adicionar(ProdutoModel produto)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _produtoRepositorio.Adicionar(produto);
                    TempData["MensagemSucesso"] = "Produto cadastrado com sucesso!";
                    return RedirectToAction("Index");
                }

                return View(produto);
            }
            catch (Exception error)
            {
                TempData["MensagemErro"] = "Ops!, não foi possível cadastrar seu produto, tente novamente!" + " Error: " + error.Message;
                return RedirectToAction("Index");
            }
        }

        public IActionResult Alterar(ProdutoModel produto)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _produtoRepositorio.AlterarProduto(produto);
                    TempData["MensagemSucesso"] = "Produto alterado com sucesso!";
                    return RedirectToAction("Index");
                }

                return View("Editar", produto);

            } catch(Exception error)
            {
                TempData["MensagemErro"] = "Ops!, não foi possível alterar o cadastro do produto, tente novamente!" + " Error: " + error.Message;
                return RedirectToAction("Index");
            }
        }

        public IActionResult Editar(int ID)
        {
            ProdutoModel produto = _produtoRepositorio.BuscaPorID(ID);
            return View(produto);
        }

        public IActionResult Excluir(int ID)
        {
            try
            {
                bool excluido = _produtoRepositorio.Excluir(ID);

                if (excluido)
                {
                    TempData["MensagemSucesso"] = "Produto excluido com sucesso!";
                }
                else
                {
                    TempData["MensagemErro"] = "Ops!, ocorreu um problema na exclusão do produto, tente novamente!";
                }

                return RedirectToAction("Index");

            }catch(Exception error)
            {
                TempData["MensagemErro"] = "Ops!, ocorreu um problema na exclusão do produto, tente novamente!" + " Error: " + error.Message;
                return RedirectToAction("Index");
            }
        }

        public IActionResult ExcluirConfirmacao(int ID)
        {
            ProdutoModel produto = _produtoRepositorio.BuscaPorID(ID);
            return View(produto);
        }
    }
}

ControleDeContatos/Controllers/UsuarioController.cs
using ControleDeContatos.Models;
using ControleDeContatos.Repositorio.Usuario;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ControleDeContatos.Controllers
{
    public class UsuarioController : Controller
    {
        private readonly iUsuarioRepositorio _usuarioRepositorio;

        public UsuarioController(iUsuarioRepositorio usuarioRepositorio)
        {
            _usuarioRepositorio = usuarioRepositorio;
        }
        
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Registrar()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Registrar(UsuarioModel usuario)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var cadastrou = _usuarioRepositorio.Registrar(usuario);
                    if (cadastrou)
                    {
                        TempData["MensagemSucesso"] = "Usuario cadastrado com sucesso!";
                        return RedirectToAction("Index", "Login");
                    }
                    else
                    {
                        TempData["MensagemErro"] = "Este email já está sendo utilizado!";
                    }
                }

                return View(usuario);
            }
            catch (Exception error)
            {
                TempData["MensagemErro"] = "Ops!, não foi possível cadastrar seu usuário, tente novamente!" + " Error: " + error.Message;
                return View(usuario);
            }
        }
    }
}

ControleDeContatos/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Controle De Contatos</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Controle De Contatos</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Página Inicial</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Contato" asp-action="Index">Contatos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Produto" asp-action="Index">Produtos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Usuario" asp-action="Index">Usuarios</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Controle De Contatos
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>